### ISSUE TITLE
dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by oleghein** [MoOx/react-svg-inline#21]
Hi,

thanks for sharing this Component!

I think the React team chose the name for [this property](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) for a good reason.

Is there any way around using this property? (except copy and pasting the SVG markup into jsx )
It would make me sleep much better ;)

best,
oleg

**Comment by MoOx** [comment]
Since this component works with raw svg as string, it does not make sense to not use innerHTML.
If you want an alternative solution, you should look for an svg to js(x) converter directly, that will make this module useless. The XSS issue cannot affect you unless you randomly display svg from a database, which is clearly not recommended.

**Comment by oleghein** [comment]
Ah ok, that makes sense. Thanks for the quick response and clarification.
